kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: arm64

services:
  - name: grpc-greeter
    image: kameshsampath/go-run
    environment:
      PORT: 9090
      GO_WORKSPACE: /drone/src
      GO_RUN_FILE: ./cmd/server/main.go

steps:
- name: gen go code
  image: kameshsampath/protoc-go
  commands:
  - |
    mkdir -p pkg/greeter
    protoc -I protos greeter.proto \
      --go_out=pkg/greeter --go-grpc_out=pkg/greeter \
      --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative 
- name: test
  image: golang:1.19
  environment:
    TARGET_SERVICE: grpc-greeter:9090
  commands:
    - |
      go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
      while ! grpcurl -plaintext "$TARGET_SERVICE" list;do sleep 3;done;
      go test -v -timeout 30s ./...